// tests/TestIR.cpp
#include "TestHelpers.hpp"

// ----------------------------------------------------------------
// AST Nodes
// ----------------------------------------------------------------

struct IntLiteral {
    int                  value;
    elpc::SourceLocation location;
};

struct BinaryExpr {
    std::string          op;  // "+", "-", "*", "/"
    IntLiteral           lhs;
    IntLiteral           rhs;
    elpc::SourceLocation location;
};

struct VarDecl {
    std::string          name;
    IntLiteral           value;
    elpc::SourceLocation location;
};

struct ReturnStmt {
    std::string          varName; // empty if literal
    IntLiteral           literal;
    bool                 usesVar;
    elpc::SourceLocation location;
};

struct ProgramNode {
    std::vector<VarDecl>    decls;
    std::vector<BinaryExpr> exprs;
    ReturnStmt              ret;
};

// ----------------------------------------------------------------
// C Backend
// Implements a simple C code generator on top of IRBuilder.
// ValueType is std::string — every emit produces a C expression.
// ----------------------------------------------------------------

class CBackend : public elpc::IRBuilder<std::string> {
public:
    explicit CBackend(elpc::DiagnosticEngine &diag)
    : elpc::IRBuilder<std::string>(diag) {}

    // --- Literal emitters ---

    std::string emitInt(int value) {
        return std::to_string(value);
    }

    // --- Arithmetic emitters ---

    std::string emitAdd(const std::string &lhs, const std::string &rhs) {
        return "(" + lhs + " + " + rhs + ")";
    }

    std::string emitSub(const std::string &lhs, const std::string &rhs) {
        return "(" + lhs + " - " + rhs + ")";
    }

    std::string emitMul(const std::string &lhs, const std::string &rhs) {
        return "(" + lhs + " * " + rhs + ")";
    }

    std::string emitDiv(const std::string &lhs, const std::string &rhs,
                        elpc::SourceLocation loc = {}) {
        // Division by zero check — caught at compile time if rhs is a literal "0"
        if (rhs == "0") {
            error("Division by zero", loc);
            return "0";
        }
        return "(" + lhs + " / " + rhs + ")";
                        }

                        std::string emitBinary(const std::string &op,
                                               const std::string &lhs,
                                               const std::string &rhs,
                                               elpc::SourceLocation loc = {}) {
                            if (op == "+") return emitAdd(lhs, rhs);
                            if (op == "-") return emitSub(lhs, rhs);
                            if (op == "*") return emitMul(lhs, rhs);
                            if (op == "/") return emitDiv(lhs, rhs, loc);
                            error("Unknown operator '" + op + "'", loc);
                            return "0";
                                               }

                                               // --- Statement emitters ---
                                               // These write into the output buffer, building up the C source

                                               void emitVarDecl(const std::string &name, const std::string &value) {
                                                   out() << "  int " << name << " = " << value << ";\n";
                                               }

                                               void emitReturn(const std::string &value) {
                                                   out() << "  return " << value << ";\n";
                                               }

                                               // --- Program structure ---

                                               void emitProgramHeader() {
                                                   out() << "// Generated by elpc\n";
                                                   out() << "#include <stdlib.h>\n\n";
                                                   out() << "int main(void) {\n";
                                               }

                                               void emitProgramFooter() {
                                                   out() << "}\n";
                                               }
};

// ----------------------------------------------------------------
// Code Generator
// Walks the AST and drives the CBackend
// ----------------------------------------------------------------

class CodeGen {
    CBackend &backend;

public:
    explicit CodeGen(CBackend &backend) : backend(backend) {}

    void generate(const ProgramNode &program) {
        backend.emitProgramHeader();
        backend.pushScope();

        for (const auto &decl : program.decls)
            generateDecl(decl);

        for (const auto &expr : program.exprs)
            generateExpr(expr);

        generateReturn(program.ret);

        backend.popScope();
        backend.emitProgramFooter();
    }

private:
    void generateDecl(const VarDecl &decl) {
        std::string val = backend.emitInt(decl.value.value);
        backend.defineVar(decl.name, decl.name, decl.location);
        backend.emitVarDecl(decl.name, val);
    }

    std::string generateExpr(const BinaryExpr &expr) {
        std::string lhs = backend.emitInt(expr.lhs.value);
        std::string rhs = backend.emitInt(expr.rhs.value);
        return backend.emitBinary(expr.op, lhs, rhs, expr.location);
    }

    void generateReturn(const ReturnStmt &ret) {
        if (ret.usesVar) {
            auto val = backend.lookupVar(ret.varName, ret.location);
            backend.emitReturn(val.value_or("0"));
        } else {
            backend.emitReturn(backend.emitInt(ret.literal.value));
        }
    }
};

// ----------------------------------------------------------------
// Test runner
// ----------------------------------------------------------------

void runIRTest(const std::string       &label,
               const ProgramNode       &program,
               const std::string       &filename = "") {
    std::cout << "\n=== " << label << " ===\n";

    elpc::DiagnosticEngine engine;
    CBackend backend(engine);
    CodeGen  codegen(backend);

    codegen.generate(program);

    if (!engine.empty()) {
        std::cout << "-- Diagnostics (" << engine.count() << ") --\n";
        engine.reportDiagnostics(std::cout);
    }

    if (!engine.hasErrors()) {
        std::cout << "-- Generated C --\n";
        std::cout << backend.result();
    }
               }

               int main() {
                   // Test 1: simple variable declarations and return
                   runIRTest("SIMPLE VAR DECL AND RETURN", ProgramNode{
                       .decls = {
                           VarDecl{ "x", IntLiteral{ 10 }, { 1, 1, "main.elpc" } },
                           VarDecl{ "y", IntLiteral{ 20 }, { 2, 1, "main.elpc" } },
                       },
                       .exprs = {},
                       .ret   = ReturnStmt{ "x", {}, true, { 3, 1, "main.elpc" } }
                   });

                   // Test 2: binary expressions
                   runIRTest("BINARY EXPRESSIONS", ProgramNode{
                       .decls = {},
                       .exprs = {
                           BinaryExpr{ "+", IntLiteral{5}, IntLiteral{3}, { 1, 1 } },
                           BinaryExpr{ "*", IntLiteral{4}, IntLiteral{7}, { 1, 5 } },
                       },
                       .ret = ReturnStmt{ "", IntLiteral{ 0 }, false, { 2, 1 } }
                   });

                   // Test 3: division by zero — caught at compile time
                   runIRTest("DIVISION BY ZERO", ProgramNode{
                       .decls = {},
                       .exprs = {
                           BinaryExpr{ "/", IntLiteral{10}, IntLiteral{0}, { 1, 1, "bad.elpc" } },
                       },
                       .ret = ReturnStmt{ "", IntLiteral{ 0 }, false, { 2, 1 } }
                   });

                   // Test 4: undefined variable in return
                   runIRTest("UNDEFINED VARIABLE", ProgramNode{
                       .decls = {
                           VarDecl{ "x", IntLiteral{ 5 }, { 1, 1, "main.elpc" } },
                       },
                       .exprs = {},
                       .ret   = ReturnStmt{ "z", {}, true, { 2, 1, "main.elpc" } }
                   });

                   // Test 5: redefined variable
                   runIRTest("REDEFINED VARIABLE", ProgramNode{
                       .decls = {
                           VarDecl{ "x", IntLiteral{ 5  }, { 1, 1, "main.elpc" } },
                           VarDecl{ "x", IntLiteral{ 10 }, { 2, 1, "main.elpc" } },
                       },
                       .exprs = {},
                       .ret   = ReturnStmt{ "x", {}, true, { 3, 1, "main.elpc" } }
                   });

                   // Test 6: filename in diagnostics
                   runIRTest("FILENAME IN DIAGNOSTICS", ProgramNode{
                       .decls = {},
                       .exprs = {
                           BinaryExpr{ "/", IntLiteral{1}, IntLiteral{0}, { 5, 12, "divide.elpc" } },
                       },
                       .ret = ReturnStmt{ "", IntLiteral{ 0 }, false, { 6, 1, "divide.elpc" } }
                   });
               }
